application: ruinmaps-hrd
version: 1
api_version: 1
runtime: python27
threadsafe: false

libraries:
- name: django
  version: "1.2"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest 

handlers:
- url: /js
  static_dir: static/js
  
- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img

- url: /docs
  static_dir: static/docs    
    
- url: /_ah/login_required
  script: main.py

- url: /trails/*
  script: main.py
  
- url: /trail/*
  script: main.py 
 
- url: .*
  script: main.py
