application: ruinmaps
version: 1
api_version: 1
runtime: python

handlers:
- url: /js
  static_dir: static/js
  
- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
  
- url: /mobile/statics
  static_dir: static/mobile
  
- url: /_ah/login_required
  script: main.py

- url: /trails/*
  script: main.py
  login: required
 
- url: .*
  script: main.py
